### ISSUE TITLE
NoClassDefFoundError with Play 2.5

### ISSUE THREAD

**Issue by resamsel** [evanbennett/play-messages#1]
When using it with Play 2.5 this plugin throws an exception while compiling the project.

```
$ activator compile
java.lang.NoClassDefFoundError: play/Play$
	at com.github.evanbennett.sbt_play_messages.PlayMessagesPlugin$.requires$lzycompute(PlayMessagesPlugin.scala:43)
	at com.github.evanbennett.sbt_play_messages.PlayMessagesPlugin$.requires(PlayMessagesPlugin.scala:43)
	at com.github.evanbennett.sbt_play_messages.PlayMessagesPlugin$.requires(PlayMessagesPlugin.scala:10)
	at sbt.Plugins$.asRequirements(Plugins.scala:281)
	at sbt.Plugins$$anonfun$3.apply(Plugins.scala:146)
	at sbt.Plugins$$anonfun$3.apply(Plugins.scala:146)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at sbt.Plugins$.deducer(Plugins.scala:146)
	at sbt.DetectedPlugins.deducePluginsFromProject(BuildStructure.scala:150)
	at sbt.Load$.resolveProject(Load.scala:660)
	at sbt.Load$.finalizeProject$1(Load.scala:559)
	at sbt.Load$.loadTransitive(Load.scala:587)
	at sbt.Load$.loadProjects$1(Load.scala:452)
	at sbt.Load$.loadUnit(Load.scala:456)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:291)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:291)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:344)
	at sbt.Load$.loadURI(Load.scala:299)
	at sbt.Load$.load(Load.scala:295)
	at sbt.Load$.load(Load.scala:286)
	at sbt.Load$.apply(Load.scala:140)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:492)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:492)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:54)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: play.Play$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.github.evanbennett.sbt_play_messages.PlayMessagesPlugin$.requires$lzycompute(PlayMessagesPlugin.scala:43)
	at com.github.evanbennett.sbt_play_messages.PlayMessagesPlugin$.requires(PlayMessagesPlugin.scala:43)
	at com.github.evanbennett.sbt_play_messages.PlayMessagesPlugin$.requires(PlayMessagesPlugin.scala:10)
	at sbt.Plugins$.asRequirements(Plugins.scala:281)
	at sbt.Plugins$$anonfun$3.apply(Plugins.scala:146)
	at sbt.Plugins$$anonfun$3.apply(Plugins.scala:146)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at sbt.Plugins$.deducer(Plugins.scala:146)
	at sbt.DetectedPlugins.deducePluginsFromProject(BuildStructure.scala:150)
	at sbt.Load$.resolveProject(Load.scala:660)
	at sbt.Load$.finalizeProject$1(Load.scala:559)
	at sbt.Load$.loadTransitive(Load.scala:587)
	at sbt.Load$.loadProjects$1(Load.scala:452)
	at sbt.Load$.loadUnit(Load.scala:456)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:291)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:291)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:344)
	at sbt.Load$.loadURI(Load.scala:299)
	at sbt.Load$.load(Load.scala:295)
	at sbt.Load$.load(Load.scala:286)
	at sbt.Load$.apply(Load.scala:140)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:492)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:492)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:54)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoClassDefFoundError: play/Play$
```

**Comment by evanbennett** [comment]
In Play 2.4, the sbt plugins were moved from `play.Play*` to `play.sbt.Play*`, along with other changes.
Accessing the Play configuration also stopped working, and at the time I was unable to resolve this, so I never updated the published code.

In Play 2.5, deprecated aliases were removed in the sbt plugin, which causes the error you are seeing.

I have reviewed the code that I have available, but I cannot find a simple fix for this. The code that I have that might work is substantially different, and due to there being no tests, I do not think it would be of much benefit, as it would likely require a lot of time to make it work.

I cannot test any of my old code, as I have updated all of my projects to use a new project that I am creating to replace this one which uses ResourceBundles.

What is your situation? (Are you starting a new project? Are you migrating an existing project? Which parts of this project are you interested in using?)

**Comment by resamsel** [comment]
I see, thanks for your thorough answer. I stumbled across this plugin and wanted to use it, as it'd solve many issues you've described (compiler tells me about missing keys, parameters are known at compile time, ...) Other features are also interesting, but I'm here for the generated message classes. If there's anything I could do to help you out in my limited time, I'll try (no Scala knowledge, apart from Play template programming).
